name: Deploy And Publish App 

on: 
  workflow_dispatch:
  pull_request:
    branches:
    - Release
    
env:
  AZURE_WEBAPP_NAME: "SocialNetworkService"
  AZURE_WEBAPP_PACKAGE_PATH:  "SocialNetworkService/publish"
  AZURE_APIM_RESOURCEGROUP: "SGGW-PZ-2023"

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: '6.0.x'
          
      - name: Restore
        run: dotnet restore SocialNetworkService.API/SocialNetworkService.API.sln
        
      - name: Build
        run: dotnet build SocialNetworkService.API/SocialNetworkService.API.sln --configuration Release --no-restore
        
      - name: Publish 
        run: dotnet publish SocialNetworkService.API/SocialNetworkService.API.sln --configuration Release --no-build --output '${{env.AZURE_WEBAPP_PACKAGE_PATH}}'

      - name: Azure Login
        run: |
          sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
          curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
          AZ_REPO=$(lsb_release -cs)
          echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
          sudo apt-get update
          sudo apt-get install azure-cli
      - uses: Azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'
      - name: Modify deployment target for WebApp
        run: az webapp config appsettings set --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group ${{ env.AZURE_APIM_RESOURCEGROUP }} --settings DEPLOYMENT_TARGET="C:\home\site\wwwroot\wwwroot"
      - name: Restart WebApp after re-config
        run: az webapp restart --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group ${{ env.AZURE_APIM_RESOURCEGROUP }}
      - name: Logout from Azure
        run: >
          az logout

      - name: Deployment 
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
